Fix llvm-objcopy shared lib build
Fix after 2bb393824aa6 ("[llvm-objcopy][COFF] Fix section name
encoding", 2022-02-21) caused "undefined reference to
`llvm::COFF::encodeSectionName" failures.