Revert "lit: revert 1a851d256d87a847bd8efc05260306258ee46931"
This reverts commit cb42519ce8a6eff50edd4ebb46caafa2d45144f7.

Causing messages like:

  File "...\Python\Python39\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 74