Fix off-by-one error when emitting diagnostics.  Also, make diagnostic a bit nicer for people who pass lots of extra arguments to calls by selecting them all instead of just the first one:
arg-duplicate.c:13:13: error: too many arguments to function
  f3 (1, 1, 2, 3, 4);   // expected-error {{too many arguments to function}}
            ^~~~~~~

This implements test/Sema/arg-duplicate.c, thanks to Neil for pointing
out this crash.

llvm-svn: 40136