improve the fixit for the missing : error when parsing ?:.  When there are already two spaces before the token where the : was expected, put the : in between the spaces.  This means we get it right in both of these cases:
t.c:2:17: error: expected ':'
  return a ? b  c;
                ^
               :
t.c:3:16: error: expected ':'
  return a ? b c;
               ^
               : 

In the later case, the diagnostic says to insert ": ", in the former
case it says to insert ":" between the spaces.  This fixes rdar://8007231

llvm-svn: 104569