Revert "[ADT] Support const-qualified unique_functions"
This reverts commit cedcaef4d6b3c8b3159c558b621cced46c08dac6.

Breaks the build:

llvm/include/llvm/ADT/FunctionExtras.h:223:7: error: explicit template argument list not allowed
  223 |       Callbacks<CallableT, CalledAs, EnableIfTrivial<CallableT>>;