Revert "Implement a new kind of Pass: dynamic pass pipeline"
This reverts commit 14db067508ca3935eb2024a7f779adf232e8d645.

Test  mlir/test/Pass:dynamic-pipeline-fail-on-parent.mlir.test fails
when run with ASAN:

ERROR: AddressSanitizer: stack-use-after-scope on address ...

Reviewed By: bkramer, pifon2a

Differential Revision: https://reviews.llvm.org/D88079