Revert "[clang] Implement Change scope of lambda trailing-return-type"
This reverts commit 9c359f58c22071a6f71d84b5445adf5da7b29415.
This broke clang bootstrap: it made existing C++ code in LLVM invalid:

llvm/include/llvm/CodeGen/LiveInterval.h:630:53: error: captured variable 'Idx' cannot appear here
              [=](std::remove_reference_t<decltype(*Idx)> V,
                                                    ^