Revert "[lldb] [gdb-remote client] Refactor handling qSupported"
This reverts commit d7aec96ee7b0cf118c84fd2964815eb7d172b85f.

It fails to build, with errors such as:
  GDBRemoteCommunicationClient.cpp:1005:20:
  error: no viable overloaded '='
          avail_name = compression;