Revert "[MLIR][Presburger] introduce SetCoalescer"
This reverts commit 56c1252bca60e7bd774d0c5cd687a32f366c812c.

The build is broken with some configurations (gcc-5 and gcc-8):

mlir/lib/Analysis/Presburger/PresburgerRelation.cpp:402:32: error: qualified name does not name a class before '{' token
 class presburger::SetCoalescer {