Revert "[lld-macho] Avoid using bump-alloc in TrieBuider"
This reverts commit 8114546ee781a357b6d27eb07edc0e4325db4b04.

That commit breaks the build with errors of the form:

/usr/local/google/home/saugustine/llvm/llvm-project/lld/MachO/ExportTrie.cpp:148:11: error: definition of implicitly declared destructor
TrieNode::~TrieNode() {