Revert "[lldb] Use nullptr instead of 0 or NULL (NFC)"
This reverts commit ca3138b0621ff19d9be8c4a69c535df38bf46c34.
Breaks building on Windows:

    ../../lldb/include\lldb/Host/HostNativeThreadBase.h(49,36): error:
        cannot initialize a member subobject of type 'lldb::thread_result_t'
        (aka 'unsigned int') with an rvalue of type 'std::nullptr_t'
      lldb::thread_result_t m_result = nullptr;
                                       ^~~~~~~
    1 error generated.