Temporarily revert "Add a facility to get system cache directory and use it in clangd"
This reverts commit 02bc5aa01cc0ad5d2c2e29e0fc1503fa25a5e68d.

As it broke building the unittests:

.../sources/llvm-project/llvm/unittests/Support/Path.cpp:334:5: error: use of undeclared identifier 'set'
    set(Value);
    ^
1 error generated.