Revert "[lldb] Upstream support for Foundation constant classes"
This reverts commit 931b18f5214be72b81d0ad79caaebda3aba1591e.

This breaks build bots witha  missing file:
/home/worker/2.0.1/lldb-x86_64-debian/llvm-project/lldb/source/Plugins/Language/ObjC/Cocoa.cpp:10:10: fatal error: 'objc/runtime.h' file not found