Revert "[MLIR][SPIRV] Start module combiner."
This reverts commit 4e2bb398cc05eeb0552cad06ea65d65b578cce92.

Shared libs build is broken linking lib/libMLIRSPIRVModuleCombiner.so:

```
ModuleCombiner.cpp:
  undefined reference to `mlir::spirv::ModuleOp::addressing_model()
```

https://buildkite.com/mlir/mlir-core/builds/8988#e3d966b9-ea43-492e-a192-b28e71e9a15b