evert "[mlir] Limit Python dependency to Development.Module when possible."
This reverts commit ce390ca5b5a91bde8285f3b42a3ea1ef11fe0d21.

The build is broken with errors like:

GPUPasses.cpp:(.text.pybind11_object_init[pybind11_object_init]+0x118): undefined reference to `PyExc_TypeError'