Revert "[LoopVectorizer] Inloop vector reductions"
This reverts commit bf411a32f556c3c525949a1a9abf3b953ea9d4b4. It breaks the build:

```
~/src/llvm-project/llvm/lib/Analysis/IVDescriptors.cpp:868:10: error: no viable conversion from returned value of type 'SmallVector<[...], 8>' to function return type 'SmallVector<[...], 4>'
  return ReductionOperations;
```