Revert "[mlir][ODS] Use StringLiteral instead of StringRef when applicable"
This reverts commit 19606701c86ae14ebe323fb8f861fda644477807 because
it breaks GCC 5 build:

  error: could not convert '(const char*)""' from 'const char*' to 'llvm::StringLiteral'
     static ::llvm::StringLiteral getDialectNamespace() { return ""; }