Revert "ADT: SmallVector size/capacity use word-size integers when elements are small"
This reverts commit df43e677eb5c1ca2b9c8ffc043d1f1c5a6475f4a.

clang-cmake-armv7-quick/llvm/llvm/lib/Support/SmallVector.cpp:81:22:
error: duplicate explicit instantiation of 'SmallVectorBase<unsigned int>'