Revert "Remove redundant "std::move"s in return statements"
The build failed with

  error: call to deleted constructor of 'llvm::Error'

errors.

This reverts commit fdc181a1a5c59d35234bc703550dfba58ec5eb35.