Revert "[lsan] On Fuchsia, don't use atexit hook for leak checks"
This reverts commit 58d38305729b18dca4de4cf2808d8a2b7261d3b4.
This reverts commit 152bc8652c91db447094c287a72aae6210c7e254.

Causes linker errors which were not fixed by the subsequent commit
either:

/home/nikic/llvm-project/compiler-rt/lib/asan/asan_rtl.cpp:503: error: undefined reference to '__asan::InstallAtExitCheckLeaks()'