Revert "[FPEnv][X86] Platform-specific builtin constrained FP enablement"
This reverts commit 69917028605d8b2714b9d844b7c294d06831d541.

Tests fail:
error: unable to create target: 'No available targets are compatible with triple "x86_64-apple-darwin"'

This happens on clang-hexagon-elf, clang-cmake-armv7-quick, and
clang-cmake-armv7-quick bots.

If anyone has any suggestions on why then I'm all ears.

Differential Revision: https://reviews.llvm.org/D73570

Revert "[FPEnv][X86] Speculative fix for failures introduced by eda495426."

This reverts commit 12e618aa589c19457925ef378ce0898546b04106.

The speculative fix didn't solve the test failures on Hexagon, ARMv6, and
MSVC AArch64.