Revert "[lldb] Use nullptr instead of 0 or NULL (NFC)"
This reverts commit 7728b6742a8671b287d67789545f7329b84e63fa.

It again broke builds on Windows:

  lldb/source/Host/common/HostNativeThreadBase.cpp(37,14): error:
  assigning to 'lldb::thread_result_t' (aka 'unsigned int') from
  incompatible type 'std::nullptr_t'