Provide anchor for compiler extensions
This patch is cherry-picked from aae32c8f968528d0fcc5ff29af071899286325fa, and
amended to prevent an undefined reference to `llvm::EnableABIBreakingChecks'

(cherry picked from commit 9857e03bc05d02dcb72cd052c955c61956de04e0)