Revert "[InferAttrs] Add writeonly to all the math functions"
This reverts commit e634b054adff16e3d26649499f40310142280110 and
b92725939db5eb98cda7457c6a0298df5945fc3b.

That commit caused crashes with compilation e.g. like this
(not fixed by the follow-up commit):

$ cat sqrt.c
float a;
b() { sqrt(a); }
$ clang -target x86_64-linux-gnu -c -O2 sqrt.c
Attributes 'readnone and writeonly' are incompatible!
  %sqrtf = tail call float @sqrtf(float %0) #1
in function b
fatal error: error in backend: Broken function found, compilation aborted!