Revert "[lld-macho] Fix symbol relocs handling for compact unwind's functionAddress"
This reverts commit 5b434d41bb2addec84f2ee583053d309cae4f6ce.

The commit in question causes:

  lld/MachO/InputFiles.cpp:916:13: error: use of undeclared identifier
  'it'